# Generated by Django 5.1.4 on 2025-01-11 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='Article_Text',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='Article_Title',
        ),
        migrations.AddField(
            model_name='post',
            name='Article_Category',
            field=models.CharField(choices=[('tech', 'Technology'), ('lifestyle', 'Lifestyle'), ('news', 'News'), ('entertainment', 'Entertainment')], default='tech', max_length=50),
        ),
    ]
