# Generated by Django 5.1.4 on 2025-01-11 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_category_rename_text_post_article_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Article_Category',
            field=models.CharField(choices=[('tech', 'Technology'), ('lifestyle', 'Lifestyle'), ('news', 'News'), ('outdoors_nature', 'Outdoors & Nature'), ('business_industrial', 'Business & Industrial'), ('computers_electronics', 'Computers & Electronics'), ('health_fitness', 'Health & Fitness'), ('arts_entertainment', 'Arts & Entertainment'), ('education', 'Education'), ('sports', 'Sports'), ('food_drink', 'Food & Drink'), ('fashion', 'Fashion')], default='tech', max_length=50),
        ),
    ]
